// <auto-generated />
using DnDHitPointsInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDHitPointsInfrastructure.Migrations
{
    [DbContext(typeof(HitPointsContext))]
    partial class HitPointsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DnDHitPointsServices.Entities.HitPoints", b =>
                {
                    b.Property<string>("CharacterName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("int");

                    b.HasKey("CharacterName");

                    b.HasIndex("CharacterName");

                    b.ToTable("HitPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
